# Install pre-commit hooks via
# pre-commit install
 
# yapf = yet another python formatter
repos:
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    language: system

# prospector: collection of python linters
- repo: git://github.com/guykisel/prospector-mirror
  rev: 7ff847e779347033ebbd9e3b88279e7f3a998b45
  hooks:
  - id: prospector
    language: system
    exclude: '^(tests/)|(examples/)'
